name: Continuous Delivery
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:    
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: ZIP build
        run: zip ${{ github.run_id }}.zip bootstrap

      - name: Upload to S3
        run: aws s3 cp ${{ github.run_id }}.zip s3://example-api-bucket/${{ github.run_id }}.zip

      - name: Update lambda function code
        run: aws lambda update-function-code --function-name view_counter --s3-bucket example-api-bucket --s3-key ${{ github.run_id }}.zip

      - name: Sleep for 5 seconds
        run: sleep 5s
        shell: bash

      - name: Release lambda function version
        run: aws lambda publish-version --function-name example-api --description ${{ github.run_id }}