name: Resume Website Backend Pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Quality-Assurance:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest boto3
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::606026656431:role/github-actions-role

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Lint Python files with ruff
        run: |
          ruff check *.py

      - name: test with pytest
        run: |
          pytest tests.py

  Deploy:
    runs-on: ubuntu-latest
    needs: [Quality-Assurance]
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: ZIP build
        run: zip ${{ github.run_id }}.zip view_counter.py

      - name: Upload to S3
        run: aws s3 cp ${{ github.run_id }}.zip s3://view-counter-api-bucket-42/${{ github.run_id }}.zip

      - name: Update lambda function code
        run: aws lambda update-function-code --function-name view_counter --s3-bucket view-counter-api-bucket-42 --s3-key ${{ github.run_id }}.zip

      - name: Sleep for 5 seconds
        run: sleep 5s
        shell: bash

      - name: Release lambda function version
        run: aws lambda publish-version --function-name view_counter --description ${{ github.run_id }}

